refactor: Refactor variables processing
eclipse-che4z/che-che4z-lsp-for-cobol pull request #1857
Opened 2023-04-25 09:19 UTC by Nurkambay

2023-04-25 09:33 UTC, ap891843 approved these changes

2023-04-25 09:54 UTC, ishche requested changes

2023-04-25 09:54 UTC, ishche commented on server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestVariableRedefineNotDefined.java
> + * Copyright (c) 2021 Broadcom.
It's 2023 already :)

2023-04-26 08:46 UTC, ishche approved these changes

2023-04-26 09:59 UTC, merged