refactor: Implementation for the new mapping
eclipse-che4z/che-che4z-lsp-for-cobol pull request #1895
Opened 2023-05-24 11:59 UTC by Nurkambay

2023-06-05 11:27 UTC, VitGottwald commented
I download the artefacts (vsix-cobol-language-support-darwin-x64.zip, vsix-idms-dialect.zip, vsix-daco-dialect.zip) and tested on internal repo. It fails on every DaCo program. Will DM you on slack.

2023-06-05 11:35 UTC, VitGottwald requested changes
Since these changes affect the core functionality and some tests were disabled, please run the internal test suite and do a manual smoke test on the internal repo before proceeding.

2023-06-07 12:14 UTC, Nurkambay commented
> Since these changes affect the core functionality and some tests were disabled, please run the internal test suite and do a manual smoke test on the internal repo before proceeding.

Thanks, I have added a use case test for it. Should be covered by unit tests now

2023-06-07 22:35 UTC, VitGottwald commented
Now both IDMS and DaCo code gets properly analysed. But now I am getting a random dance of errors showing up and disappearing when enter code. Maybe worth running the _typing test_?

2023-06-08 10:57 UTC, Nurkambay commented
> 

Looks like it is something broken in the processing itself, i will check it in dev

2023-06-08 14:07 UTC, ishche approved these changes

2023-06-09 08:59 UTC, ap891843 commented on server/common/src/main/java/org/eclipse/lsp/cobol/common/mapping/ExtendedTextLine.java
> +    result.characters.clear();
I guess this is not necessary.

2023-06-09 09:52 UTC, Nurkambay commented
> Now both IDMS and DaCo code gets properly analysed. But now I am getting a random dance of errors showing up and disappearing when enter code. Maybe worth running the _typing test_?

I have checked it. It is completely the same functionality as we have on development. Looks like when we have errors we have faster processing then expected and that's why we can see these errors. And we have the same in the development branch.

2023-06-09 11:15 UTC, ap891843 approved these changes
👍

2023-06-09 11:16 UTC, merged