fix: warn the usage of deprecated cobol 5 compiler directives
eclipse-che4z/che-che4z-lsp-for-cobol pull request #2040
Opened 2023-08-31 09:46 UTC by ap891843

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Use deprecated compile directives in the code (for e.g. NOCMPR2), should show a warning message

## Checklist:
- [ ] Each of my commits contains one meaningful change
- [ ] I have performed rebase of my branch on top of the development
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

2023-08-31 10:44 UTC, zeibura requested changes

2023-08-31 10:44 UTC, zeibura commented on server/engine/src/main/resources/resourceBundles/messages_en.properties
> +compilerDirective.deprecatedDirectiveUse=%s is deprecated compile directive
%s is a deprecated compiler directive

2023-09-04 08:19 UTC, ap891843 commented on server/engine/src/main/resources/resourceBundles/messages_en.properties
> +compilerDirective.deprecatedDirectiveUse=%s is deprecated compile directive
updated

2023-09-04 10:34 UTC, ishche approved these changes

2023-09-04 14:38 UTC, merged