DE575629 - Most program has errors in SQL-ERROR-RTN paragraph
eclipse-che4z/che-che4z-lsp-for-cobol pull request #2210
Opened 2024-01-23 12:33 UTC by ilidio-lopes

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:
- [x] Each of my commits contains one meaningful change
- [x] I have performed rebase of my branch on top of the development
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

2024-02-14 08:28 UTC, ap891843 commented on server/engine/src/main/java/org/eclipse/lsp/cobol/core/model/VariableUsageUtils.java
> +    for (VariableNode variableNode : definedVariables.values()) {
we could have used stream API 
```java
definedVariables.values()
            .stream().flatMap(Node::getDepthFirstStream)
            .filter(VariableNode.class::isInstance)
            .map(VariableNode.class::cast)
            .filter(var -> var.getName().equals("name"))
            .findFirst();
```

2024-02-14 08:30 UTC, ap891843 requested changes
I suggest to add a UseCase test for this

2024-02-21 08:19 UTC, ishche commented
Please update the PR description and squash commits.

2024-02-21 11:49 UTC, ilidio-lopes commented
> Please update the PR description and squash commits.

I cannot squash. Probably because I don't have write permission.

2024-02-26 09:37 UTC, ap891843 approved these changes
LGTM

2024-02-26 09:38 UTC, ishche approved these changes

2024-02-26 10:14 UTC, merged