XML data host and file reference variables
eclipse-che4z/che-che4z-lsp-for-cobol pull request #2365
Opened 2024-07-02 08:51 UTC by ilidio-lopes

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Check the test cases in the PR . XML data host variables can be in a sample code

```cobol
        Identification Division.
        Program-Id. 'TEST1'.
        Data Division.
         Working-Storage Section.
       01 VAR3 USAGE IS SQL TYPE IS XML AS CHARACTER LARGE OBJECT (10 M).
       01 VAR-NAME4 USAGE IS SQL TYPE IS XML AS CHAR LARGE OBJECT (10 G).
       01  VAR-NAME5 USAGE IS SQL TYPE IS XML AS CLOB (20)
       01  VAR-NAME6 USAGE IS SQL TYPE IS XML AS DBCLOB (30 K)
       01  VAR-NAME7 USAGE IS SQL TYPE IS XML AS BLOB-LOCATOR.
       01  VAR-NAME8 USAGE IS SQL TYPE IS XML AS CLOB-LOCATOR.
        PROCEDURE division
```

![image](https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol/assets/54845983/f87683b0-23b3-462b-955d-7d57f09abcfc)

- [ ] Test A
- [ ] Test B

## Checklist:
- [x] Each of my commits contains one meaningful change
- [x] I have performed rebase of my branch on top of the development
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

2024-07-15 14:38 UTC, Nurkambay commented
@ilidio-lopes please resolve conflicts

2024-07-17 14:27 UTC, ap891843 commented on server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/sql/TestSqlHostVariable.java
> +                  + "       01 {$*VAR-NAME12} USAGE IS SQL TYPE IS XML AS  DBCLOB-FILE.\n"
Can we add a use case for level 2-48 and a level 49 with error

2024-07-17 14:29 UTC, ap891843 commented
I suggest rebase with development. Can see 2 unnecessary commits  bdc108051dce63bf1233ff2d639b6ef2d4e17a2c and 5890e351d3c6c7fd114d8f90c0ec63558af61dd0

2024-07-17 14:31 UTC, ap891843 requested changes
add a use case for level 2-48 and a level 49 with error

2024-07-18 08:48 UTC, ap891843 commented on server/engine/src/test/java/org/eclipse/lsp/cobol/lsp/SourceUnitGraphTest.java
> +    assertFalse(sourceUnitGraph.isUserSuppliedCopybook(URI));
These changes looks like are from 8bd8a7135735dd185a3a0a6aebd042b6e19260fb , and unrelate to this PR

2024-07-19 07:50 UTC, amanPras approved these changes

2024-07-19 07:51 UTC, merged