Fix converse v3
eclipse-che4z/che-che4z-lsp-for-cobol pull request #2541
Opened 2024-10-16 18:13 UTC by mm-broadcom

Further fixes to CONVERSE to address defects found in previous implementation(s).

## How Has This Been Tested?

Ran existing tests

## Checklist:
- [x] Each of my commits contains one meaningful change
- [x] I have performed rebase of my branch on top of the development
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

2024-10-21 18:47 UTC, mm-broadcom commented
@slavek-kucera Would it be possible for you to review this?

2024-10-25 13:40 UTC, KutluOzel-b requested changes

2024-10-25 13:40 UTC, KutluOzel-b commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSConverseOptionsCheckUtility.java
> +        checkHasMandatoryOptions(ctx.cics_converse_tolength(), ctx, "TOLENGTH OR TOFLENGTH");
isn't a mandatory options when they used with FROMLENGTH even if they are shown mandatory on docs. 
![image](https://github.com/user-attachments/assets/aeb5cf8d-46e4-45c3-aedf-8b8830fb51f8)

however they are mandatory when used with MAXFLENGTH or MAXLENGTH  them like this case;

![image](https://github.com/user-attachments/assets/4bccc7e0-cc26-4a5d-9f14-73921cd55b97)

2024-10-25 13:40 UTC, KutluOzel-b commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSConverseOptionsCheckUtility.java
> +            checkHasIllegalOptions(ctx.cics_converse_erase(), "CTLCHAR");
typo , change it to ERASE and good 
![image](https://github.com/user-attachments/assets/8d367088-bf47-4f8a-8893-1f240ff44bdb)

2024-11-06 19:31 UTC, mm-broadcom commented
@KutluOzel-b Both things you brought up have been addressed.

2024-11-07 07:42 UTC, KutluOzel-b commented
LGTM 👍

2024-11-07 07:58 UTC, slavek-kucera approved these changes

2024-11-07 07:58 UTC, slavek-kucera commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSConverseOptionsCheckUtility.java
> +        }
This should be upgraded to one of those mutually exclusive check functions to avoid generating confusing diagnostics.

2024-11-07 13:33 UTC, merged