Cics TRANSFORM improvements
eclipse-che4z/che-che4z-lsp-for-cobol pull request #2549
Opened 2024-10-22 13:39 UTC by mm-broadcom

## How Has This Been Tested?

Implemented tests for both valid and invalid use case(s).

## Checklist:
- [x] Each of my commits contains one meaningful change
- [x] I have performed rebase of my branch on top of the development
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

2024-10-25 13:18 UTC, KutluOzel-b requested changes

2024-10-25 13:18 UTC, KutluOzel-b commented on server/engine/src/main/antlr4/org/eclipse/lsp/cobol/implicitDialects/cics/CICSLexer.g4
> +TRANSFORMER : T R A N S F O R M E R;
Add keyword completion suggestions to new tokens.

2024-10-25 13:18 UTC, KutluOzel-b commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSTransformOptionsCheckUtility.java
> +            checkHasMandatoryOptions(ctx.XMLTRANSFORM(), ctx, "XMLTRANSFORM");
![image](https://github.com/user-attachments/assets/d86af28f-12d2-48c6-96df-4a8fc5aaccd6)

Even XMLCONTAINER is optional in the docs it is mandatory on compiler.

2024-10-25 13:18 UTC, KutluOzel-b commented on server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestCICSTransform.java
> +    private static final String BASE_TEXT =
We don't need this after CICSTestUtils class.

2024-10-25 13:18 UTC, KutluOzel-b commented on server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestCICSTransform.java
> +
Add more invalid cases

2024-10-25 13:18 UTC, KutluOzel-b commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSTransformOptionsCheckUtility.java
> +                    put(CICSLexer.TYPENAME, ErrorSeverity.ERROR);
![image](https://github.com/user-attachments/assets/527fe9ac-24c8-4f79-9b10-6edd8e5fd9fb)

Check which options are giving errors instead of warnings on duplication. TYPENAME should give warning due to it can be compiled.

2024-10-25 13:18 UTC, KutluOzel-b commented on server/engine/src/main/antlr4/org/eclipse/lsp/cobol/implicitDialects/cics/CICSParser.g4
> +cics_transform_xml: (DATATOXML|XMLTODATA) ((CHANNEL | DATCONTAINER | XMLCONTAINER | NSCONTAINER) cics_data_value | (ELEMNAME | ELEMNAMELEN | ELEMNS | ELEMNSLEN | TYPENAME | TYPENAMELEN | TYPENS | TYP
I suggest to make optional command ordering as flexible as compiler does. an example : 

`       IDENTIFICATION DIVISION.
       PROGRAM-ID. ABCDEF.
       DATA DIVISION.

       WORKING-STORAGE SECTION.
        01 EXCI-EXEC-RETURN-CODE.
          02 EXEC-RESP        PIC 9(8) COMP.
          02 EXEC-RESP2       PIC 9(8) COMP.
          02 EXEC-ABCODE      PIC X(4).
          02 EXEC-MSG-LEN     PIC 9(8) COMP.
          02 EXEC-MSG-PTR     POINTER.
       PROCEDURE DIVISION.
           EXEC CICS
           TRANSFORM  DATATOXML CHANNEL(EXCI-EXEC-RETURN-CODE)
           DATCONTAINER(EXCI-EXEC-RETURN-CODE)
           XMLCONTAINER(EXCI-EXEC-RETURN-CODE)
           ELEMNAME(EXCI-EXEC-RETURN-CODE)
           XMLTRANSFORM('asd')

                   END-EXEC.
`
![image](https://github.com/user-attachments/assets/300ae762-1c4c-4d81-8a20-83c6d67d8b5f)
![image](https://github.com/user-attachments/assets/02ff0347-fd17-4b9c-8ddd-4a8da3412d35)

2024-10-25 13:39 UTC, mm-broadcom commented on server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestCICSTransform.java
> +    private static final String BASE_TEXT =
You do for tests with errors

2024-10-25 13:45 UTC, KutluOzel-b commented on server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestCICSTransform.java
> +    private static final String BASE_TEXT =
CICSTestUtils#errorTest method is injecting template. You do not need to rewrite this.

2024-11-25 14:15 UTC, mm-broadcom commented
@ilidio-lopes Could you review this?

2025-01-13 19:31 UTC, mm-broadcom commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSTransformOptionsCheckUtility.java
> +                    put(CICSLexer.TYPENAME, ErrorSeverity.ERROR);
Resolved in latest commit.

2025-01-13 19:31 UTC, mm-broadcom commented on server/engine/src/main/antlr4/org/eclipse/lsp/cobol/implicitDialects/cics/CICSParser.g4
> +cics_transform_xml: (DATATOXML|XMLTODATA) ((CHANNEL | DATCONTAINER | XMLCONTAINER | NSCONTAINER) cics_data_value | (ELEMNAME | ELEMNAMELEN | ELEMNS | ELEMNSLEN | TYPENAME | TYPENAMELEN | TYPENS | TYP
Resolved in latest commits.

2025-01-14 09:16 UTC, slavek-kucera commented on server/engine/src/main/antlr4/org/eclipse/lsp/cobol/implicitDialects/cics/CICSParser.g4
New tokens should be added to cicsLexerDefinedVariableUsageTokens.

2025-01-14 09:16 UTC, slavek-kucera commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSTransformOptionsCheckUtility.java
> +                    put(CICSLexer.ELEMNAME, ErrorSeverity.WARNING);
These appear to produce errors when duplicates are encountered:
```
 LINE           SOURCE LISTING                                                                                      
                                                                                                                    
00001                     EXEC CICS                                                00070000                         
00002                     TRANSFORM XMLTODATA CHANNEL(CH)                          00070101                         
00003                     ELEMNAME(E) ELEMNAMELEN(EL)                              00070301                         
00004                     ELEMNAME(E) ELEMNAMELEN(EL)                              00070401                         
00005                     XMLCONTAINER(XMLC)                                       00070501                         
00006                     END-EXEC                                                 00071000                         
00007                                                                              00079400                         
CICS 7.3.0 COMMAND LANGUAGE TRANSLATOR                                            TIME 04.02 DATE 14 JAN 25   PAGE 2
TRANSLATOR DIAGNOSTIC MESSAGES OF SEVERITY W AND ABOVE.                                                             
MESSAGE NUMBER  SEVERITY  LINE NUMBER     MESSAGE                                                                   
DFH7036I           W        00001         PROGRAM DOES NOT BEGIN WITH AN IDENTIFICATION DIVISION.                   
DFH7220I           C        00001         MULTIPLE OCCURRENCE OF 'ELEMNAME' KEYWORD IS IGNORED.                     
DFH7220I           C        00001         MULTIPLE OCCURRENCE OF 'ELEMNAMELEN' KEYWORD IS IGNORED.                  
END OF TRANSLATOR DIAGNOSTIC MESSAGES.                                                                              
```

2025-01-14 09:16 UTC, slavek-kucera commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSTransformOptionsCheckUtility.java
> +    private void checkJSON(CICSParser.Cics_transform_jsonContext ctx) {
Exactly one of DATATOJSON or JSONTODATA.

2025-01-14 09:16 UTC, slavek-kucera commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSTransformOptionsCheckUtility.java
> +        if (!ctx.DATATOXML().isEmpty()) {
Exactly one of DATATOXML or XMLTODATA.

2025-01-14 09:16 UTC, slavek-kucera commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSTransformOptionsCheckUtility.java
> +        checkPrerequisiteIsMet(ctx.TYPENS(), ctx.TYPENSLEN(), ctx, "TYPENS");
`ELEMNAME without ELEMNAMELEN` and so on.

2025-01-14 09:16 UTC, slavek-kucera commented on server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestCICSTransform.java
> +
test cases for DATATOXML and XMLTODATA cannot be specified together similarly for JSON.

2025-01-14 15:43 UTC, mm-broadcom commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSTransformOptionsCheckUtility.java
> +                    put(CICSLexer.ELEMNAME, ErrorSeverity.WARNING);
Those are severity of "information" as the message number ends in "I" for the multiple occurrence.

2025-01-14 15:50 UTC, slavek-kucera commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSTransformOptionsCheckUtility.java
> +                    put(CICSLexer.ELEMNAME, ErrorSeverity.WARNING);
SEVERITY=C, job terminates with RC=8.

2025-01-14 15:50 UTC, mm-broadcom commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSTransformOptionsCheckUtility.java
> +    private void checkJSON(CICSParser.Cics_transform_jsonContext ctx) {
Added in a later commit.

2025-01-14 15:51 UTC, mm-broadcom commented on server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestCICSTransform.java
> +
They're just grouped here as the ANTLR rules are set up as bidirectional, albeit with checks. The tests are done separately when they're called.

2025-01-14 15:53 UTC, mm-broadcom commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSTransformOptionsCheckUtility.java
> +                    put(CICSLexer.ELEMNAME, ErrorSeverity.WARNING);
The CICS severity codes are E, I, W, S: https://www.ibm.com/docs/en/cics-ts/5.6?topic=messages-severity-codes

Severity C for TYPENAME was only an error though: https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol/pull/2549#discussion_r1816641217

2025-01-14 16:37 UTC, mm-broadcom commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSTransformOptionsCheckUtility.java
> +                    put(CICSLexer.ELEMNAME, ErrorSeverity.WARNING);
Fixed in latest commit.

2025-01-14 16:45 UTC, mm-broadcom commented on server/engine/src/main/antlr4/org/eclipse/lsp/cobol/implicitDialects/cics/CICSParser.g4
Resolved in latest commit.

2025-01-14 17:00 UTC, slavek-kucera commented on server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestCICSTransform.java
> +
The tests are missing.

2025-01-14 17:06 UTC, mm-broadcom commented on server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestCICSTransform.java
> +
@slavek-kucera https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol/pull/2549/commits/7ea4a374acfd6efa14671668325912981d62e9b5 ?

2025-01-14 17:07 UTC, slavek-kucera commented on server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestCICSTransform.java
> +
for `checkHasExactlyOneOption("DATATOJSON or JSONTODATA"...` and `checkHasExactlyOneOption("DATATOXML or XMLTODATA"...`

2025-01-14 17:23 UTC, mm-broadcom commented on server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestCICSTransform.java
> +
Added in latest commit.

2025-01-15 09:49 UTC, slavek-kucera approved these changes

2025-01-15 10:09 UTC, merged