CICS SEND Command Implementation
eclipse-che4z/che-che4z-lsp-for-cobol pull request #2556
Opened 2024-10-24 10:35 UTC by ilidio-lopes

## How Has This Been Tested?

- [x] Unit tests CICS Send parser rules

## Checklist:
- [x] Each of my commits contains one meaningful change
- [x] I have performed rebase of my branch on top of the development
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

2024-11-27 09:53 UTC, KutluOzel-b requested changes

2024-11-27 09:53 UTC, KutluOzel-b commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSSendOptionsCheckUtility.java
> +  private void checkGroup1(CICSParser.Cics_send_group1Context ctx) {
I think better to add missing message for LENGTH or FLENGTH requires FROM in all groups

2024-11-27 09:53 UTC, KutluOzel-b commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSSendOptionsCheckUtility.java
> +    if (!ctx.DEFAULT().isEmpty() || !ctx.ALTERNATE().isEmpty()) {
Although it is stated as this is docs, ERASE is not mandatory to use DEFAULT or ALTERNATE 
![image](https://github.com/user-attachments/assets/8ce309da-7d38-4c95-98be-ca37560cf272)

2024-11-27 09:53 UTC, KutluOzel-b commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSSendOptionsCheckUtility.java
> +    checkHasMutuallyExclusiveOptions("STRFIELD or CTLCHAR", ctx.STRFIELD(), ctx.CTLCHAR());
ATTACHID also conflicts with CTLCHAR
![image](https://github.com/user-attachments/assets/04c962e3-ac2c-40c2-acda-0f2834491d0f)

2024-11-27 09:53 UTC, KutluOzel-b commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSSendOptionsCheckUtility.java
> +    checkHasMutuallyExclusiveOptions("PASSBK or CBUFF", ctx.PASSBK(), ctx.CBUFF());
PASSBK CBUFF and CNOTCOMPL are mutual exclusive 
![image](https://github.com/user-attachments/assets/49955e94-742d-4ef9-92f7-b1df2c95e1cb)

2024-11-27 09:53 UTC, KutluOzel-b commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSSendOptionsCheckUtility.java
> +  private void checkGroup1(CICSParser.Cics_send_group1Context ctx) {
FROM is required when FMH is in use
![image](https://github.com/user-attachments/assets/6988f6c9-a18e-425e-a1ab-085cb9b18561)

2024-11-27 11:49 UTC, ilidio-lopes commented
All comments addressed in the last commit

2024-11-27 12:15 UTC, KutluOzel-b commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSOptionsCheckUtility.java
> -        CICSAssignOptionsCheckUtility.RULE_INDEX,
Its good to keep this :)

2024-11-27 13:16 UTC, ilidio-lopes commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSOptionsCheckUtility.java
> -        CICSAssignOptionsCheckUtility.RULE_INDEX,
it is :)

2024-11-27 13:34 UTC, ilidio-lopes commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSOptionsCheckUtility.java
> -        CICSAssignOptionsCheckUtility.RULE_INDEX,
fix pushed

2024-11-27 13:57 UTC, KutluOzel-b approved these changes
Looks good

2024-12-05 09:02 UTC, ap891843 commented
@KutluOzel-b Thanks for the review

2024-12-05 09:02 UTC, merged