Implementation of VERIFY statement in CICS
eclipse-che4z/che-che4z-lsp-for-cobol pull request #2583
Opened 2024-11-18 16:11 UTC by ilidio-lopes

## How Has This Been Tested?

- [x] Unit tests CICS VERIFY parser rules

## Checklist:
- [x] Each of my commits contains one meaningful change
- [x] I have performed rebase of my branch on top of the development
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

2024-11-29 09:07 UTC, KutluOzel-b requested changes

2024-11-29 09:07 UTC, KutluOzel-b commented on server/engine/src/main/antlr4/org/eclipse/lsp/cobol/implicitDialects/cics/CICSLexer.g4
> +ENCRYPTKEY : E N C R Y P T K E Y;
Add new tokens to keyword suggestions

2024-12-19 11:34 UTC, slavek-kucera requested changes

2024-12-19 11:34 UTC, slavek-kucera commented on server/engine/src/main/antlr4/org/eclipse/lsp/cobol/implicitDialects/cics/CICSParser.g4
> +                (TOKENTYPE | DATATYPE) cics_cvda | BASICAUTH | JWT | KERBEROS | BIT | BASE64 | OUTTOKEN cics_ref | cics_handle_response)*;
At least one parameter must be specified.

2024-12-19 11:34 UTC, slavek-kucera commented on server/engine/src/main/antlr4/org/eclipse/lsp/cobol/implicitDialects/cics/CICSLexer.g4
> +TOKENTYPE : T O K E N T Y P E;
Verify if the new tokens should be included in the `cicsLexerDefinedVariableUsageTokens` rule.

2024-12-19 11:34 UTC, slavek-kucera commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSVerifyOptionsCheckUtility.java
> +              put(CICSLexer.VERIFY, ErrorSeverity.ERROR);
Not one of the arguments.

2025-01-02 11:59 UTC, ilidio-lopes commented
all comments addressed on the latest commit

2025-01-02 12:16 UTC, slavek-kucera commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSVerifyOptionsCheckUtility.java
> +    checkHasMutuallyExclusiveOptions("BIT or DATATYPE or BASE64", ctx.BIT(), ctx.DATATYPE(), ctx.BASE64());
It looks like `OUTTOKENLEN` requires `OUTTOKEN`.

It looks like the `ESMREASON` and `ESMRESP` require the same relation, but I am not sure as I am unable to build any examples.

2025-01-02 13:19 UTC, ilidio-lopes commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSVerifyOptionsCheckUtility.java
> +    checkHasMutuallyExclusiveOptions("BIT or DATATYPE or BASE64", ctx.BIT(), ctx.DATATYPE(), ctx.BASE64());
I checked with the compiler and ESMREASON does not require ESMRESP. The opposite is also true.

> It looks like `OUTTOKENLEN` requires `OUTTOKEN`.
> 
> It looks like the `ESMREASON` and `ESMRESP` require the same relation, but I am not sure as I am unable to build any examples.

I checked with the compiler and ESMREASON does not require ESMRESP. The opposite is also true.

2025-01-02 13:41 UTC, slavek-kucera approved these changes

2025-01-02 13:41 UTC, merged