Implementation of HANDLE statement in CICS
eclipse-che4z/che-che4z-lsp-for-cobol pull request #2592
Opened 2024-11-20 11:07 UTC by ilidio-lopes

## How Has This Been Tested?

- [x] Unit tests CICS HANDLE parser rules

## Checklist:
- [x] Each of my commits contains one meaningful change
- [x] I have performed rebase of my branch on top of the development
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

2024-11-29 09:37 UTC, KutluOzel-b requested changes

2024-11-29 09:37 UTC, KutluOzel-b commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSHandleOptionsCheckUtility.java
> +    checkHasToManyOneOptions(ctx);
```suggestion
    checkHasTooManyOptions(ctx);
```

2024-11-29 09:37 UTC, KutluOzel-b commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSOptionsCheckBaseUtility.java
> +  protected void checkHasToManyOneOptions(ParserRuleContext parentCtx) {
```suggestion
  protected void checkHasTooManyOptions(ParserRuleContext parentCtx) {
```

2024-11-29 09:37 UTC, KutluOzel-b commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSOptionsCheckBaseUtility.java
> +              ErrorSeverity.ERROR, getLocality(parentCtx), "To many options provided for: ", "HANDLE AID");
```suggestion
              ErrorSeverity.ERROR, getLocality(parentCtx), "Too many options provided for: ", "HANDLE AID");
```

2024-11-29 09:37 UTC, KutluOzel-b commented on server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestCICSAddSubevent.java
> +                                new Range(new Position(14, 12), new Position(14, 20)),
```suggestion
                                new Range(),
```

2024-11-29 09:37 UTC, KutluOzel-b commented on server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestCICSAsktime.java
> +                                new Range(new Position(15, 12), new Position(15, 20)),
```suggestion
                                new Range(),
```

2024-11-29 09:37 UTC, KutluOzel-b commented on server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestCICSBif.java
> +                                new Range(new Position(14, 12), new Position(18, 18)),
```suggestion
                                new Range(),
```

2024-11-29 09:37 UTC, KutluOzel-b commented on server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestCICSBif.java
> +                                new Range(new Position(17, 12), new Position(17, 15)),
```suggestion
                                new Range(),
```

2024-11-29 09:37 UTC, KutluOzel-b commented on server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestCICSBif.java
> +                                new Range(new Position(18, 12), new Position(18, 18)),
```suggestion
                                new Range(),
```

2024-11-29 09:37 UTC, KutluOzel-b commented on server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestCICSBif.java
> +                                new Range(new Position(14, 12), new Position(16, 26)),
```suggestion
                                new Range(),
```

2024-11-29 09:37 UTC, KutluOzel-b commented on server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestCICSBif.java
Sorry about my trash left there. I'll remove them . Please change the lines on failing tests after committing the suggestions then I can add more suggestions

2025-01-07 15:35 UTC, ilidio-lopes commented
Issues addressed on the latest commit

2025-01-08 09:24 UTC, slavek-kucera commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSHandleOptionsCheckUtility.java
> +              put(CICSLexer.AID, ErrorSeverity.ERROR);
Duplicate `AID` seems to produce only a warning.

2025-01-08 09:29 UTC, slavek-kucera commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSOptionsCheckBaseUtility.java
> +    }
Given the dependency on `AID` keyword and the hardcoded message, this should be move to `CICSHandleOptionsCheckUtility.java`.

Also does it work correctly if you specify `aid` (lowercase)?

2025-01-08 09:30 UTC, slavek-kucera commented on server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestCICSHandle.java
> +          "HANDLE {CONDITION|errorOne}";
This should be a valid case.

2025-01-08 09:50 UTC, slavek-kucera commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSHandleOptionsCheckUtility.java
> +    checkHasMandatoryOptions(ctx.cics_conditions(), ctx, "CICS CONDITION");
At the same time the `CONDITION` keyword is mandatory.

2025-01-09 14:10 UTC, slavek-kucera commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSHandleOptionsCheckUtility.java
> +    }
The imports must be cleaned up...
```suggestion
    if (parentCtx.children == null)
      return;
    long commandOptionsCount = parentCtx.children.stream()
            .filter(node -> node instanceof TerminalNode)
            .map(TerminalNode.class::cast)
            .filter(node -> node.getSymbol().getType() != CICSLexer.AID)
            .count();
    if (commandOptionsCount > 16) {
      throwException(ErrorSeverity.ERROR, getLocality(parentCtx), "Too many options provided for: ", "HANDLE AID");
    }
```

2025-01-09 15:09 UTC, slavek-kucera approved these changes

2025-01-09 15:09 UTC, merged