fix endbr defects DE621202 & DE621201
eclipse-che4z/che-che4z-lsp-for-cobol pull request #2596
Opened 2024-11-20 14:54 UTC by ilidio-lopes

## How Has This Been Tested?

Autocempletion
![image](https://github.com/user-attachments/assets/b9cedea4-d1ea-4d40-ac6d-4b31ebef45e4)

Error message
![image](https://github.com/user-attachments/assets/91de8d91-bc92-4f2f-b5fa-3a3999be77c2)
![image](https://github.com/user-attachments/assets/2f863b72-723f-40dd-bdb2-5b2a88299437)

- [x] Unit tests CICS ENDBR parser rules

## Checklist:
- [x] Each of my commits contains one meaningful change
- [x] I have performed rebase of my branch on top of the development
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

2024-12-19 13:52 UTC, slavek-kucera requested changes

2024-12-19 13:52 UTC, slavek-kucera commented on server/engine/src/main/antlr4/org/eclipse/lsp/cobol/implicitDialects/cics/CICSParser.g4
> +cics_endbr_endbrowse: cics_endbr | cics_endbrowse;
I think this should follow the pattern from the other rules
```
cics_endbr: ENDBR cics_endbr_opts;
cics_endbrowse: ENDBROWSE cics_endbrowse_opts;
```

2025-01-07 12:45 UTC, slavek-kucera commented on server/engine/src/main/antlr4/org/eclipse/lsp/cobol/implicitDialects/cics/CICSParser.g4
> +cics_endbrowse_opts: (ACTIVITY | CONTAINER | EVENT | PROCESS | TIMER | (BROWSETOKEN | RETCODE) cics_data_value | cics_handle_response)+;
Where does the `RETCODE` come from?

2025-01-07 12:47 UTC, slavek-kucera commented on server/engine/src/main/antlr4/org/eclipse/lsp/cobol/implicitDialects/cics/CICSParser.g4
> +cics_endbrowse_opts: (ACTIVITY | CONTAINER | EVENT | PROCESS | TIMER | (BROWSETOKEN | RETCODE) cics_data_value | cics_handle_response)+;
found it.

2025-01-07 13:05 UTC, slavek-kucera commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSEndBrowseOptionsUtility.java
>            put(CICSLexer.ACTIVITY, ErrorSeverity.WARNING);
Duplicate `RETCODE` is an error:
```
 LINE           SOURCE LISTING                                                                                        
                                                                                                                      
00001                     EXEC CICS                                                00070000                           
00002                     ENDBROWSE CONTAINER BROWSETOKEN(B)                       00070101                           
00003                     RETCODE(R)                                               00070201                           
00004                     RETCODE(R)                                               00070301                           
00005                     END-EXEC                                                 00071000                           
00006                                                                              00079400                           
CICS 7.3.0 COMMAND LANGUAGE TRANSLATOR                                            TIME 08.02 DATE 7 JAN 25    PAGE 2  
TRANSLATOR DIAGNOSTIC MESSAGES OF SEVERITY W AND ABOVE.                                                               
MESSAGE NUMBER  SEVERITY  LINE NUMBER     MESSAGE                                                                     
DFH7017I           W                      MESSAGES WERE ISSUED DURING OPTIONS PROCESSING - REFER TO TOP OF LISTING FOR
                                          FURTHER DETAILS.                                                            
DFH7036I           W        00001         PROGRAM DOES NOT BEGIN WITH AN IDENTIFICATION DIVISION.                     
DFH7220I           C        00001         MULTIPLE OCCURRENCE OF 'RETCODE' KEYWORD IS IGNORED.                        
```

2025-01-07 13:06 UTC, slavek-kucera commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSEndBrowseOptionsUtility.java
`RETCODE` is only mandatory in the `EXCI` mode.

2025-01-07 13:07 UTC, slavek-kucera commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSEndbrOptionsUtility.java
> +          put(CICSLexer.FILE, ErrorSeverity.ERROR);
`DATASET` should be included as well.

2025-01-07 13:57 UTC, ilidio-lopes commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSEndBrowseOptionsUtility.java
> `RETCODE` is only mandatory in the `EXCI` mode.

This means I should remove RETCODE?

2025-01-07 14:50 UTC, slavek-kucera commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSEndBrowseOptionsUtility.java
Comment out the validation code for now and add TODO please.

2025-01-08 09:58 UTC, slavek-kucera approved these changes

2025-01-08 09:59 UTC, slavek-kucera commented on server/engine/src/main/resources/LanguageKeywords.txt
> +DATASET=
Already in the list.
```suggestion
```

2025-01-08 10:20 UTC, merged