Fix CICS Formattime Command
eclipse-che4z/che-che4z-lsp-for-cobol pull request #2599
Opened 2024-11-21 08:52 UTC by KutluOzel-b

## Checklist:
- [x] Each of my commits contains one meaningful change
- [x] I have performed rebase of my branch on top of the development
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

2024-11-29 08:31 UTC, ilidio-lopes requested changes

2024-11-29 08:31 UTC, ilidio-lopes commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSFormatTimeOptionsCheckUtility.java
> +                }
Error for parametrized options

2024-11-29 08:31 UTC, ilidio-lopes commented
Has conflicts

2024-11-29 14:22 UTC, KutluOzel-b commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSFormatTimeOptionsCheckUtility.java
> +                }
adressed in latest commit

2024-11-29 15:00 UTC, ilidio-lopes approved these changes

2024-12-11 13:32 UTC, slavek-kucera commented on server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestCICSFormatTimeStatement.java
> +            "FORMATTIME {ABSTIME(100) TIMESEP | errorMissingTime}";
```
DFH7226I           E        00002         SUB-OPERAND '100' OF 'DATE' KEYWORD SHOULD BE A DATA REFERENCE NOT AN   
                                          EXPRESSION OR A CONSTANT. COMMAND NOT TRANSLATED.                       
DFH7226I           E        00005         SUB-OPERAND '100' OF 'ABSTIME' KEYWORD SHOULD BE A DATA REFERENCE NOT AN
                                          EXPRESSION OR A CONSTANT. COMMAND NOT TRANSLATED.                       
DFH7226I           E        00008         SUB-OPERAND '100' OF 'ABSTIME' KEYWORD SHOULD BE A DATA REFERENCE NOT AN
                                          EXPRESSION OR A CONSTANT. COMMAND NOT TRANSLATED.                       
```

2024-12-11 15:20 UTC, slavek-kucera approved these changes

2024-12-11 15:29 UTC, slavek-kucera commented on server/engine/src/main/antlr4/org/eclipse/lsp/cobol/implicitDialects/cics/CICSLexer.g4
> +STRINGZONE: S T R I N G Z O N E;
Should this be also added to the `cicsLexerDefinedVariableUsageTokens` rule?

2024-12-12 08:08 UTC, merged