Implementation of SPOOLOPEN statement in CICS
eclipse-che4z/che-che4z-lsp-for-cobol pull request #2608
Opened 2024-11-22 17:13 UTC by ilidio-lopes

## How Has This Been Tested?

- [x] Unit tests CICS SPOOLOPEN parser rules

## Checklist:
- [x] Each of my commits contains one meaningful change
- [x] I have performed rebase of my branch on top of the development
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

2024-12-05 09:28 UTC, KutluOzel-b commented on server/engine/src/main/antlr4/org/eclipse/lsp/cobol/implicitDialects/cics/CICSParser.g4
> +cics_spoolopen_input: (INPUT | TOKEN cics_data_area | USERID cics_data_value | CLASS cics_data_value | NOHANDLE | cics_handle_response)*;
```suggestion
cics_spoolopen_input: (INPUT | TOKEN cics_data_area | USERID cics_data_value | CLASS cics_data_value | cics_handle_response)*;
```
as handlers are already added

2024-12-19 11:49 UTC, slavek-kucera requested changes

2024-12-19 11:49 UTC, slavek-kucera commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSSpoolOpenOptionsCheckUtility.java
> +              put(CICSLexer.SPOOLOPEN, ErrorSeverity.ERROR);
This is not an operand.

2024-12-19 11:49 UTC, slavek-kucera commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSSpoolOpenOptionsCheckUtility.java
> +    checkHasMandatoryOptions(ctx.INPUT(), ctx, "INPUT");
USERID is mandatory.

2024-12-19 11:49 UTC, slavek-kucera commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSSpoolOpenOptionsCheckUtility.java
> +    checkHasMandatoryOptions(ctx.OUTPUT(), ctx, "OUTPUT");
USERID mandatory as well.

2025-01-02 14:27 UTC, ilidio-lopes commented
Issues fixed in the latest commit

2025-01-02 14:47 UTC, slavek-kucera approved these changes

2025-01-02 15:05 UTC, merged