Implementation of IGNORE statement in CICS
eclipse-che4z/che-che4z-lsp-for-cobol pull request #2612
Opened 2024-11-25 09:30 UTC by ilidio-lopes

## How Has This Been Tested?

- [x] Unit tests CICS IGNORE parser rules

## Checklist:
- [x] Each of my commits contains one meaningful change
- [x] I have performed rebase of my branch on top of the development
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

2024-12-19 11:56 UTC, slavek-kucera requested changes

2024-12-19 11:56 UTC, slavek-kucera commented on server/engine/src/main/antlr4/org/eclipse/lsp/cobol/implicitDialects/cics/CICSParser.g4
> +cics_ignore_options :  (CONDITION | cics_conditions | cics_handle_response)+;
There is a lot of conditions missing in `cics_conditions` 
https://www.ibm.com/docs/en/cics-ts/6.x?topic=reference-eib-fields#dfhp4au__title__17

2024-12-19 11:56 UTC, slavek-kucera commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSIgnoreOptionsCheckUtility.java
> +        checkDuplicates(ctx);
The conditions need to be checked for duplicates.
```
 LINE           SOURCE LISTING                                                                                      
                                                                                                                    
00001                     EXEC CICS                                                00070000                         
00002                     IGNORE CONDITION INVLDC INVLDC                           00070101                         
00003                     END-EXEC                                                 00071000                         
00004                                                                              00079400                         
CICS 7.3.0 COMMAND LANGUAGE TRANSLATOR                                            TIME 06.54 DATE 19 DEC 24   PAGE 2
TRANSLATOR DIAGNOSTIC MESSAGES OF SEVERITY W AND ABOVE.                                                             
MESSAGE NUMBER  SEVERITY  LINE NUMBER     MESSAGE                                                                   
DFH7036I           W        00001         PROGRAM DOES NOT BEGIN WITH AN IDENTIFICATION DIVISION.                   
DFH7220I           C        00001         MULTIPLE OCCURRENCE OF 'INVLDC' KEYWORD IS IGNORED.                       
END OF TRANSLATOR DIAGNOSTIC MESSAGES.                                                                              
```

2024-12-19 11:56 UTC, slavek-kucera commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSIgnoreOptionsCheckUtility.java
> +        checkDuplicates(ctx);
Also add tests for this situation.

2025-01-06 17:49 UTC, slavek-kucera commented on server/engine/src/main/antlr4/org/eclipse/lsp/cobol/implicitDialects/cics/CICSLexer.g4
> +NORMAL : N O R M A L;
Should this be added also into the `CICS.tmLanguage.json`?

Also please re-sort all the lists (not-just in this file).

2025-01-06 17:55 UTC, slavek-kucera commented on server/engine/src/main/antlr4/org/eclipse/lsp/cobol/implicitDialects/cics/CICSParser.g4
> +cics_handle_condition: CONDITION ((cics_conditions | cicsWord) cics_label? | cics_handle_response)+ EOF?;
`EOF?` does not make sense to me.

2025-01-07 07:40 UTC, ilidio-lopes commented on server/engine/src/main/antlr4/org/eclipse/lsp/cobol/implicitDialects/cics/CICSParser.g4
> +cics_handle_condition: CONDITION ((cics_conditions | cicsWord) cics_label? | cics_handle_response)+ EOF?;
> `EOF?` does not make sense to me.

if  EOF is part of a rule that can be repeated zero or more times ('*' or '+') it results in this error
`error(186): CICSParser. g4:416:0: rule cics_handle_condition contains a closure with at least one alternative that can match EOF`

2025-01-07 08:00 UTC, slavek-kucera commented on server/engine/src/main/antlr4/org/eclipse/lsp/cobol/implicitDialects/cics/CICSParser.g4
> +cics_handle_condition: CONDITION ((cics_conditions | cicsWord) cics_label? | cics_handle_response)+ EOF?;
My question is why did you add it to the rule in the first place? `EOF?` means maybe end - it can never fail parsing.

2025-01-07 08:41 UTC, slavek-kucera commented on server/engine/src/main/antlr4/org/eclipse/lsp/cobol/implicitDialects/cics/CICSParser.g4
> +cics_conditions: NORMAL | ERROR | RDATT | WRBRK | EODS | EOC | INBFMH | ENDINPT | NONVAL | NOSTART | TERMIDERR | FILENOTFOUND | NOTFND | DUPREC | DUPKEY |
There seems to be one more condition `EOF` - the token will have to be named differently e.g. EOF_TOKEN.

2025-01-07 09:05 UTC, ilidio-lopes commented on server/engine/src/main/antlr4/org/eclipse/lsp/cobol/implicitDialects/cics/CICSParser.g4
> +cics_conditions: NORMAL | ERROR | RDATT | WRBRK | EODS | EOC | INBFMH | ENDINPT | NONVAL | NOSTART | TERMIDERR | FILENOTFOUND | NOTFND | DUPREC | DUPKEY |
> There seems to be one more condition `EOF` - the token will have to be named differently e.g. EOF_TOKEN.

What do you mean? I don't see other EOF.

2025-01-07 09:20 UTC, slavek-kucera commented on server/engine/src/main/antlr4/org/eclipse/lsp/cobol/implicitDialects/cics/CICSParser.g4
> +cics_conditions: NORMAL | ERROR | RDATT | WRBRK | EODS | EOC | INBFMH | ENDINPT | NONVAL | NOSTART | TERMIDERR | FILENOTFOUND | NOTFND | DUPREC | DUPKEY |
https://www.ibm.com/docs/en/cics-ts/6.x?topic=reference-eib-fields#dfhp4au__title__27
```
04 EOF
```

2025-01-07 10:56 UTC, slavek-kucera commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSIgnoreOptionsCheckUtility.java
> +                    put(CICSLexer.CONDITION, ErrorSeverity.ERROR);
warning.

2025-01-07 12:35 UTC, slavek-kucera approved these changes

2025-01-07 12:35 UTC, merged