Implementation of LOAD statement in CICS
eclipse-che4z/che-che4z-lsp-for-cobol pull request #2613
Opened 2024-11-25 09:59 UTC by ilidio-lopes

## How Has This Been Tested?

- [x] Unit tests CICS LOAD parser rules

## Checklist:
- [x] Each of my commits contains one meaningful change
- [x] I have performed rebase of my branch on top of the development
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

2024-12-19 11:59 UTC, slavek-kucera requested changes

2024-12-19 11:59 UTC, slavek-kucera commented on server/engine/src/main/antlr4/org/eclipse/lsp/cobol/implicitDialects/cics/CICSParser.g4
> +cics_load_options: (PROGRAM cics_name | (SET |  ENTRY) cics_ref | (LENGTH | FLENGTH) cics_data_area | HOLD | cics_handle_response)*;
```suggestion
cics_load_options: (PROGRAM cics_name | (SET |  ENTRY) cics_ref | (LENGTH | FLENGTH) cics_data_area | HOLD | cics_handle_response)+;
```

2024-12-19 11:59 UTC, slavek-kucera commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSLoadOptionsCheckUtility.java
> +              put(CICSLexer.LOAD, ErrorSeverity.ERROR);
This is not a valid operand.

2024-12-19 11:59 UTC, slavek-kucera commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSOptionsCheckUtility.java
> +        new CICSLoadOptionsCheckUtility(context, errors));  }
```suggestion
    optionsMap.put(
        CICSLoadOptionsCheckUtility.RULE_INDEX,
        new CICSLoadOptionsCheckUtility(context, errors));
  }
```

2025-01-02 15:16 UTC, ilidio-lopes commented
issues addressed on the latest commit

2025-01-02 15:30 UTC, slavek-kucera approved these changes

2025-01-02 15:35 UTC, merged