Implementation of MONITOR statement in CICS
eclipse-che4z/che-che4z-lsp-for-cobol pull request #2614
Opened 2024-11-25 10:24 UTC by ilidio-lopes

## How Has This Been Tested?

- [x] Unit tests CICS MONITOR parser rules

## Checklist:
- [x] Each of my commits contains one meaningful change
- [x] I have performed rebase of my branch on top of the development
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

2024-12-19 12:10 UTC, slavek-kucera requested changes

2024-12-19 12:10 UTC, slavek-kucera commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSMonitorOptionsCheckUtility.java
> +              put(CICSLexer.MONITOR, ErrorSeverity.ERROR);
Not an operand.

2024-12-19 12:10 UTC, slavek-kucera commented on server/engine/src/main/antlr4/org/eclipse/lsp/cobol/implicitDialects/cics/CICSParser.g4
> +cics_monitor_options: (POINT cics_data_value | (DATA1 | DATA2 | ENTRYNAME) cics_data_area | cics_handle_response)*;
```suggestion
cics_monitor_options: (POINT cics_data_value | (DATA1 | DATA2 | ENTRYNAME) cics_data_area | cics_handle_response)+;
```

2024-12-19 12:10 UTC, slavek-kucera commented on server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/utility/CICSOptionsCheckUtility.java
> +        new CICSMonitorOptionsCheckUtility(context, errors));  }
```suggestion
    optionsMap.put(
        CICSMonitorOptionsCheckUtility.RULE_INDEX,
        new CICSMonitorOptionsCheckUtility(context, errors));
  }
```

2025-01-02 15:25 UTC, ilidio-lopes commented
All issues addressed

2025-01-02 15:33 UTC, slavek-kucera approved these changes

2025-01-02 16:00 UTC, merged